# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appstore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'SVProgressHUD'
pod 'HandyJSON', '~> 4.2.0'
pod 'Moya'
pod 'Kingfisher'
pod 'MJExtension'
pod 'MJRefresh'
pod 'EasyPeasy'
  # Pods for appstore

end
